- name: Grab VPC details
  amazon.aws.ec2_vpc_net_info:
    region: "{{ ec2_region }}"
    filters:
      "tag:Environment": "{{ ec2_environment }}"
  register: all_vpcs

- name: Delete Route Table
  ansible.builtin.include_tasks: delete_rt_table.yml

- name: Delete Internet Gateway
  ansible.builtin.include_tasks: delete_igw.yml

- name: Delete Subnet
  ansible.builtin.include_tasks: delete_subnet.yml

- name: Delete Security Group
  ansible.builtin.include_tasks: delete_security_group.yml

- name: Delete VPC
  ansible.builtin.include_tasks: delete_vpc.yml

- name: Delete SSH Key Pair
  ansible.builtin.include_tasks: delete_key_pair.yml
