# Play 1: Create an instance on AWS
- name: Create EC2 instance
  hosts: localhost
  become: false
  gather_facts: true
  vars_files:
    - ./vars/aws_common.yml

  roles:
    - {role: check_vars, when: not skip_check}

  tasks:
    - name: Check if SSH key exists
      ansible.builtin.stat:
        path: "{{ temp_dir }}/{{ ssh_key_filename }}.pub"
      register: key

    - name: Fail if SSH key not found
      fail:
        msg: "SSH key is not found in {{ temp_dir }}. Make sure that `make generate-ssh-key` completes successfully."
      when: not key.stat.exists

    - name: Store SSH pub Key in a fact
      ansible.builtin.set_fact:
        pub_key: "{{ lookup('file', path) }}"
      vars:
        path: "{{ temp_dir }}/{{ ssh_key_filename }}.pub"

    - name: Include Linux distribution variables
      ansible.builtin.include_vars: "./vars/aws_{{ ec2_distro }}.yml"

    - name: Create EC2 instance in AWS
      ansible.builtin.include_role:
        name: aws_create_ec2

    - name: Grab facts for the instance we just created
      amazon.aws.ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          instance-state-name: running
          "tag:Name": "{{ ec2_name_tag }}"
      register: ansible_node_facts

    - name: Set facts for next play
      ansible.builtin.set_fact:
        instance_name: "{{ ec2_name_tag }}"

    - name: Add instance(s) to my_instances group
      ansible.builtin.add_host:
        name: "{{ item.tags.Name }}"
        ansible_host: "{{ item.public_dns_name }}"
        ansible_user: "{{ ec2_username }}"
        public_ip: "{{ item.public_ip_address }}"
        private_ip: "{{ item.private_ip_address }}"
        instance_name: "{{ ec2_resource_prefix }}"
        ansible_ssh_private_key_file: "{{ temp_dir }}/{{ ssh_key_filename }}"
        instance_region: "{{ ec2_region }}"
        instance_ssh: "{{ ssh_info }}"
        instance_scp: "{{ scp_info }}"
        instance_grafana: "{{ grafana_info }}"
        groups:
          - my_instances
      with_items: "{{ ansible_node_facts.instances }}"


# Play 2: Configure the instance we created
- name: Configure Instance(s)
  hosts: "my_instances"
  gather_facts: true
  vars_files:
    - ./vars/go_inputs.yml
    - ./vars/clab_inputs.yml
    - ./vars/aws_common.yml

  pre_tasks:
    - name: Display variables/facts known for instance
      debug:
        msg: "Running {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }}), IP address: {{ ansible_host }}"

  roles:
    - {role: configure_instance, become: true}

  tasks:
    - name: Print out instance information for the user
      ansible.builtin.debug:
        msg:
          - "SSH: {{ hostvars[inventory_hostname]['instance_ssh'] }}"
          - "To upload cEOS image: {{ hostvars[inventory_hostname]['instance_scp'] }}"
          - "To connect to Grafana (once deployed): {{ hostvars[inventory_hostname]['instance_grafana'] }}"
      when:
        - hostvars[inventory_hostname]['instance_ssh'] is defined
        - hostvars[inventory_hostname]['instance_scp'] is defined
        - hostvars[inventory_hostname]['instance_grafana'] is defined
