- name: Provision EC2 instance
  amazon.aws.ec2_instance:
    name: "{{ ec2_name_tag }}"
    region: "{{ ec2_region }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ec2_ami_id }}"
    key_name: "{{ ec2_resource_prefix }}-key"
    vpc_subnet_id: "{{ create_subnet.subnet.id }}"
    network:
      assign_public_ip: true
    security_group: "{{ ec2_resource_prefix }}-SG"
    wait: true
    volumes: "{{ ec2_volume }}"
    tags:
      Environment: "{{ ec2_environment }}"
  register: ec2
