- name: Create SSH Key Pair
  ansible.builtin.include_tasks: create_key_pair.yml

- name: Create VPC
  ansible.builtin.include_tasks: create_vpc.yml

- name: Create Security Group
  ansible.builtin.include_tasks: create_security_group.yml

- name: Create Subnet
  ansible.builtin.include_tasks: create_subnet.yml

- name: Create Internet Gateway
  ansible.builtin.include_tasks: create_igw.yml

- name: Create Route Table
  ansible.builtin.include_tasks: create_rt_table.yml

- name: Provision EC2 Instance
  ansible.builtin.include_tasks: create_ec2_instance.yml

- name: Save region information
  ansible.builtin.template:
    src: region.j2
    dest: "{{ temp_dir }}/.region"
    unsafe_writes: true
  delegate_to: localhost

- name: Get EC2 info (and retry to give it time to get the public IP address)
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      "tag:Name": "{{ ec2_name_tag }}"
      "tag:Environment": "{{ ec2_environment }}"
      # 0 (pending), 16 (running), 32 (shutting-down), 48 (terminated), 64 (stopping), and 80 (stopped)
      instance-state-code: ["0", "16"]
  register: ec2
  until: ec2.instances[0].public_ip_address is defined
  retries: 30
  delay: 10

- name: Save VM URL
  ansible.builtin.template:
    src: vm.j2
    dest: "{{ temp_dir }}/.vm"
    unsafe_writes: true
  delegate_to: localhost

- name: Save access details
  ansible.builtin.set_fact:
    ssh_info: >
      ssh -i lab-state/{{ ssh_key_filename }}
      {{ ec2_username }}@{{ ec2.instances[0].public_dns_name }}

- name: Save access details
  ansible.builtin.set_fact:
    scp_info: >
      scp -i lab-state/{{ ssh_key_filename }} {{ path_to_image }}/{{ ceos_image }}
      {{ ec2_username }}@{{ ec2.instances[0].public_dns_name }}:./network-automation-with-go

- name: Save grafana details
  ansible.builtin.set_fact:
    grafana_info: http://{{ ec2.instances[0].public_dns_name }}:3000

- name: Wait until we can SSH to the instance
  ansible.builtin.wait_for:
    host: "{{ ec2.instances[0].public_ip_address }}"
    port: 22
    state: started
