- name: Install Ansible Collections
  community.general.ansible_galaxy_install:
    type: collection
    name: "{{ item }}"
    dest: "collections"
  loop: "{{ ansible_collections }}"
  become: false
